apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstageCT
  description: |
    Backstage ,We try to implement CT features in BS.
  links:
    - title: Website
      url: https://controltower-dev.cicd.rnd.amadeus.net/
    - title: Documentation
      url: https://backstage.io/docs
    - title: Storybook
      url: https://backstage.io/storybook
    - title: Discord Chat
      url: https://discord.com/invite/EBHEGzX
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: url:https://github.com/backstage/backstage
    lighthouse.com/website-url: https://backstage.io
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: ct-catalog
