apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jenkinsCtcom
  description: jenkins Ctcomponent
  tags:
    - java
    - data
  links:
    - url: https://example.com/user
      title: Examples Users
      icon: user
spec:
  type: service
  lifecycle: experimental
  owner: team-a
  system: artist-engagement-portal
  
