apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jenkinsCT
  description: Jenkins CT component
  tags:
    - rest
  links:
   - url: https://example.com/user
     title: Examples Users
     icon: user
spec:
  type: service
  lifecycle: experimental
  owner: bhatts
  
